import {
  collection,
  addDoc,
  getDocs,
  query,
  where,
  serverTimestamp
} from 'firebase/firestore';
import { ref, uploadString, getDownloadURL } from 'firebase/storage';
import { db, storage } from '../config/firebase';
import jsPDF from 'jspdf';
import { GeneratedDocument } from './aiService';
import {
  loadBereitLogo,
  addLogoToPDF,
  addFooterLogoToPDF,
  formatDocumentContent,
  isHeader
} from '../utils/pdfHelpers';
import { logEvent, logError } from './loggingService';

export interface OnboardingPackageData {
  employeeName: string;
  email: string;
  role: string;
  startDate: string;
  location: string;
  department: string;
  reportingManager: string;
  certifications: string[];
  language: string;
  systemAccess: string[];
  vpnAccess: boolean;
  emailSetup: boolean;
  equipmentNeeded: string[];
  documents: GeneratedDocument[];
  status: 'draft' | 'active' | 'completed';
  progress: number;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

const generatePDF = async (doc: GeneratedDocument, employeeName: string): Promise<jsPDF> => {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - (margin * 2);

  let yPosition = margin;

  // Load logo once and reuse for all pages
  const logo = await loadBereitLogo();

  // Add bereit logo using helper function
  await addLogoToPDF(pdf, margin, yPosition, logo);

  yPosition += 25;

  // Add title
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text(doc.title, margin, yPosition);
  yPosition += 10;

  // Add employee name
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Employee: ${employeeName}`, margin, yPosition);
  yPosition += 15;

  // Add content with proper text wrapping and pagination
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');

  // Format document content using helper function
  const paragraphs = formatDocumentContent(doc.content);
  const footerBuffer = margin + 25;

  for (const cleanText of paragraphs) {
    // Check if it's a header using helper function
    const isHeaderText = isHeader(cleanText);

    if (isHeaderText) {
      // Add some spacing before headers
      yPosition += 5;
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(12);
    } else {
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(11);
    }

    // Split text to fit width
    const lines = pdf.splitTextToSize(cleanText, maxWidth);

    for (const line of lines) {
      // Check if we need a new page
      if (yPosition > pageHeight - footerBuffer) {
        pdf.addPage();
        yPosition = margin;
        await addLogoToPDF(pdf, margin, yPosition, logo);
        yPosition += 25;
        pdf.setFont('helvetica', isHeaderText ? 'bold' : 'normal');
      }

      pdf.text(line, margin, yPosition);
      yPosition += 7;
    }

    // Add spacing after paragraph
    yPosition += 3;
  }

  // Add footer on all pages
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);

    // Footer line
    pdf.setDrawColor(200, 200, 200);
    pdf.line(margin, pageHeight - 20, pageWidth - margin, pageHeight - 20);

    // Add footer logo using helper function
    await addFooterLogoToPDF(pdf, margin, pageHeight - 17, logo);

    // Footer text - left side
    pdf.setTextColor(100, 100, 100);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.text('Generated by bereit.works', margin + 22, pageHeight - 12);

    // Date and time - left side (below generated text)
    const now = new Date();
    const dateStr = now.toLocaleDateString('de-DE');
    const timeStr = now.toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' });
    pdf.text(`${dateStr} ${timeStr}`, margin + 22, pageHeight - 7);

    // Page number - center of page
    const pageText = `Page ${i} of ${totalPages}`;
    const pageTextWidth = pdf.getTextWidth(pageText);
    pdf.text(pageText, (pageWidth - pageTextWidth) / 2, pageHeight - 12);
  }

  return pdf;
};

export const createOnboardingPackage = async (data: OnboardingPackageData) => {
  try {
    logEvent('info', 'Creating onboarding package', {
      employee: data.employeeName,
      email: data.email,
      documentCount: data.documents.length,
    });

    // Generate PDFs for each document
    const pdfUrls = await Promise.all(
      data.documents.map(async (doc) => {
        const pdf = await generatePDF(doc, data.employeeName);

        // Convert to blob
        const pdfBlob = pdf.output('blob');
        
        // Convert blob to base64 for Firebase upload
        const reader = new FileReader();
        const base64Promise = new Promise<string>((resolve) => {
          reader.onloadend = () => resolve(reader.result as string);
          reader.readAsDataURL(pdfBlob);
        });
        const base64Data = await base64Promise;
        
        // Upload to Firebase Storage
        const storageRef = ref(
          storage,
          `documents/${data.email}/${doc.type}_${Date.now()}.pdf`
        );
        await uploadString(storageRef, base64Data, 'data_url');
        const url = await getDownloadURL(storageRef);
        
        return {
          ...doc,
          pdfUrl: url,
        };
      })
    );

    // Save to Firestore
    const docRef = await addDoc(collection(db, 'onboardingPackages'), {
      ...data,
      documents: pdfUrls,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    });

    logEvent('info', 'Onboarding package stored', {
      employee: data.employeeName,
      packageId: docRef.id,
    });

    return { success: true, id: docRef.id, documents: pdfUrls };
  } catch (error) {
    logError('Error creating onboarding package', {
      employee: data.employeeName,
      email: data.email,
      error: error instanceof Error ? error.message : String(error),
    });
    return { success: false, error };
  }
};

export const getOnboardingPackages = async (createdBy?: string) => {
  try {
    let q;
    if (createdBy) {
      q = query(collection(db, 'onboardingPackages'), where('createdBy', '==', createdBy));
    } else {
      q = collection(db, 'onboardingPackages');
    }
    
    const snapshot = await getDocs(q);
    const packages = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
    
    return { success: true, data: packages };
  } catch (error) {
    console.error('Error fetching packages:', error);
    return { success: false, error };
  }
};
