import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { ref, uploadString, getDownloadURL } from 'firebase/storage';
import { db, storage } from '../config/firebase';
import jsPDF from 'jspdf';
import { VisaDocument } from './visaAiService';
import {
  loadBereitLogo,
  addLogoToPDF,
  addFooterLogoToPDF,
  formatDocumentContent,
  isHeader,
} from '../utils/pdfHelpers';
import { logEvent, logError } from './loggingService';

export interface VisaPackageData {
  employeeName: string;
  email: string;
  nationality: string;
  currentLocation: string;
  visaType: string;
  jobTitle: string;
  salary: string;
  startDate: string;
  educationLevel: string;
  yearsExperience: string;
  germanLevel: string;
  documents: VisaDocument[];
  packageType: 'visa';
  status: 'draft' | 'active' | 'completed';
  createdBy: string;
  createdAt: string;
}

const generatePDF = async (doc: VisaDocument, employeeName: string): Promise<jsPDF> => {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - (margin * 2);

  let yPosition = margin;

  // Load logo once and reuse for all pages
  const logo = await loadBereitLogo();

  // Add bereit logo using helper function
  await addLogoToPDF(pdf, margin, yPosition, logo);

  yPosition += 25;

  // Add title
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text(doc.title, margin, yPosition);
  yPosition += 10;

  // Add employee name
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Applicant: ${employeeName}`, margin, yPosition);
  yPosition += 15;

  // Add content
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');

  // Format document content using helper function
  const paragraphs = formatDocumentContent(doc.content);
  const footerBuffer = margin + 25;

  for (const cleanText of paragraphs) {
    const isHeaderText = isHeader(cleanText);

    if (isHeaderText) {
      yPosition += 5;
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(12);
    } else {
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(11);
    }

    const lines = pdf.splitTextToSize(cleanText, maxWidth);

    for (const line of lines) {
      if (yPosition > pageHeight - footerBuffer) {
        pdf.addPage();
        yPosition = margin;
        await addLogoToPDF(pdf, margin, yPosition, logo);
        yPosition += 25;
        pdf.setFont('helvetica', isHeaderText ? 'bold' : 'normal');
      }

      pdf.text(line, margin, yPosition);
      yPosition += 7;
    }

    yPosition += 3;
  }

  // Add footer on all pages
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);

    pdf.setDrawColor(200, 200, 200);
    pdf.line(margin, pageHeight - 20, pageWidth - margin, pageHeight - 20);

    // Add footer logo using helper function
    await addFooterLogoToPDF(pdf, margin, pageHeight - 17, logo);

    // Footer text - left side
    pdf.setTextColor(100, 100, 100);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.text('Generated by bereit.works', margin + 22, pageHeight - 12);

    // Date and time - left side (below generated text)
    const now = new Date();
    const dateStr = now.toLocaleDateString('de-DE');
    const timeStr = now.toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' });
    pdf.text(`${dateStr} ${timeStr}`, margin + 22, pageHeight - 7);

    // Page number - center of page
    const pageText = `Page ${i} of ${totalPages}`;
    const pageTextWidth = pdf.getTextWidth(pageText);
    pdf.text(pageText, (pageWidth - pageTextWidth) / 2, pageHeight - 12);
  }

  return pdf;
};

export const createVisaPackage = async (data: VisaPackageData) => {
  logEvent('info', 'Creating visa package', {
    employee: data.employeeName,
    email: data.email,
    documentCount: data.documents.length,
  });

  try {
    logEvent('debug', 'Generating visa package PDFs', { count: data.documents.length });
    const pdfUrls = await Promise.all(
      data.documents.map(async (doc: VisaDocument, index: number) => {
        logEvent('debug', 'Generating visa package document', {
          index: index + 1,
          total: data.documents.length,
          title: doc.title,
        });

        const pdf = await generatePDF(doc, data.employeeName);
        const pdfBlob = pdf.output('blob');
        const reader = new FileReader();
        const base64Promise = new Promise<string>((resolve) => {
          reader.onloadend = () => resolve(reader.result as string);
          reader.readAsDataURL(pdfBlob);
        });
        const base64Data = await base64Promise;
        const storagePath = `documents/${data.email}/visa_${doc.type}_${Date.now()}.pdf`;
        const storageRef = ref(storage, storagePath);
        await uploadString(storageRef, base64Data, 'data_url');
        const url = await getDownloadURL(storageRef);

        logEvent('info', 'Uploaded visa package document', { title: doc.title, storagePath });

        return {
          ...doc,
          pdfUrl: url,
        };
      })
    );

    logEvent('debug', 'Persisting visa package to Firestore');
    const docRef = await addDoc(collection(db, 'onboardingPackages'), {
      ...data,
      documents: pdfUrls,
      packageType: 'visa',
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    });

    logEvent('info', 'Visa package stored', {
      employee: data.employeeName,
      packageId: docRef.id,
    });
    return { success: true, id: docRef.id, documents: pdfUrls };
  } catch (error) {
    logError('Error creating visa package', {
      employee: data.employeeName,
      email: data.email,
      error: error instanceof Error ? error.message : String(error),
    });
    return { success: false, error };
  }
};
